name: Docker Image CI

on:
  push:
    branches: [ latest, master, mpichdiy ]
    tags:
      - '*'
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ latest, master, mpichdiy ]
  workflow_dispatch:

jobs:

  push_to_registries:
    name: Build and push Docker image to GitHub registries
    runs-on: ubuntu-latest
    environment: dockerhub
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag          
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
