name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-nova-sl7:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build novaexperiment/sl7:latest
      run: docker build . --file Dockerfile --tag novaexperiment/sl7:latest


  build-nova-sl7-mpich:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build novaexperiment/sl7:mpichdiy
      run: docker build . --file Dockerfile_mpichdiy --tag novaexperiment/sl7:mpichdiy
